"$schema" = "schemas/schema.json"

[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-load",
  "allow-execute",
  "allow-batch",
  "allow-select",
  "allow-close",
  "allow-get-config",
  "allow-sync"
]
