"$schema" = "schemas/schema.json"

[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-load",
  "allow-execute",
  "allow-select",
  "allow-close",
  "allow-get-config"
]
